confidence: 0.1
model_path: "detect/train3/weights/best.pt"
video_path: "seafloor_footage.mp4"
output_path: "seafloor_footage_annotated.mp4"
iou_threshold: 0.2
csv_path: "spreadsheet.csv"
display_x-axis: 1280
display_y-axis: 720

